services:
  - type: web
    name: whatsapp-bot-apartemen
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node bot-wweb.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
